import Vapor
import Fluent
import FluentSQL

struct DatabaseSeeder {
    func clear(on db: any Database) async throws {
        guard let sql = db as? any SQLDatabase else { return }

        try await sql.raw("DELETE FROM cells;").run()
        try await sql.raw("DELETE FROM categories;").run()
        try await sql.raw("DELETE FROM users;").run()
        try await sql.raw("DELETE FROM tokens;").run()
    }

    func seed(on db: any Database) async throws {
        try await Cell.query(on: db).delete()
        try await Category.query(on: db).delete()

        let foodCategory = Category(title: "Еда",
                                    type: "food",
                                    image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/categoryfood.jpg")
        let leisureCategory = Category(title: "Развлечения",
                                       type: "leisure",
                                       image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/categoryleisure.jpg")
        let fraudCategory = Category(title: "Безопасность",
                                     type: "fraud",
                                     image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/categoryfraud.jpg")
        let healthCategory = Category(title: "Здоровье",
                                      type: "health",
                                      image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/categoryhealth.jpg")
        let cultureCategory = Category(title: "Культура",
                                       type: "culture",
                                       image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/categoryculture.jpg")

        try await foodCategory.save(on: db)
        try await leisureCategory.save(on: db)
        try await fraudCategory.save(on: db)
        try await healthCategory.save(on: db)
        try await cultureCategory.save(on: db)

        let cellsData = [makeCell(categoryID: try foodCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/foodrisk-1.jpg",
                              title: "Уличная еда без риска",
                              subtitle: "Как есть безопасно в Латинской Америке",
                              date: seedDate(month: 1, day: 8),
                              readingTime: 6,
                              description: "Уличная еда — самый быстрый способ почувствовать город, но для новичка это легко превращается в рулетку. Главное правило: идите туда, где стоит очередь из местных. Большой поток гостей значит, что продукты не залеживаются. Обращайте внимание на разделение ролей: в хороших точках один человек принимает оплату, другой готовит. Если один и тот же повар делает всё сразу — лучше пройти мимо. В жарких странах избегайте льда в напитках и нарезанных фруктов, которые долго лежат на витрине. Блюда с глубокой термообработкой обычно безопаснее сырых закусок. Держите в аптечке сорбенты и электролиты — они спасут первые сутки, если любопытство окажется сильнее осторожности.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/foodrisk-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/foodrisk-3.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try foodCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/seoulfood-1.jpg",
                              title: "Сеул без острого перца",
                              subtitle: "Нежные блюда корейской кухни для новичков",
                              date: seedDate(month: 1, day: 22),
                              readingTime: 7,
                              description: "Корейская кухня — не только острые соусы. Попробуйте соллонтан: молочный суп из говяжьих костей, который варят часами — он пресный, соль добавляете сами. Самгетхан — курица с рисом и женьшенем, без перца и идеальна после долгой прогулки. Пулькоги — тонкая говядина в сладком соевом маринаде с грушей. В ресторанах просите «ан ольманы хэ чу сэё» — «не остро, пожалуйста». Бибимбап можно заказать без кочудян или с соусом отдельно. Металлические палочки удобнее деревянных, а миску с рисом в Сеуле не поднимают — едят ложкой и палочками. Так вы попробуете Корею без «огня» во рту.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/seoulfood-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/seoulfood-3.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try foodCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/coffeeitaly-1.jpg",
                              title: "Кофе в Италии до одиннадцати",
                              subtitle: "Почему капучино пьют только утром",
                              date: seedDate(month: 2, day: 3),
                              readingTime: 5,
                              description: "В Италии кофе — ритуал с чёткими правилами. Капучино и любые молочные напитки пьют до 11:00: после обеда горячее молоко считают тяжёлым для желудка. После пасты заказывают эспрессо — короткий, без сиропов. У стойки (al banco) кофе в два-три раза дешевле, чем за столиком (al tavolo): выпили эспрессо за минуту и пошли дальше — так делают местные. «Latte» — это стакан молока; «caffè latte» — кофе с молоком. К эспрессо часто подают воду: выпейте глоток до и после. В баре сначала закажите у кассира, получите чек, отдайте бариста — так не создаёте очередь у стойки.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/coffeeitaly-2.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try foodCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/sushitokyo-1.jpg",
                              title: "Лучшие суши в Токио",
                              subtitle: "Где искать свежие морепродукты сегодня",
                              date: seedDate(month: 2, day: 17),
                              readingTime: 6,
                              description: "После переезда рынка с Цукидзи гастрономия сосредоточилась на Тоёсу и во внешних рядах старого Цукидзи. Аукцион тунца начинается около четырёх утра — место лучше бронировать заранее, но за едой можно прийти и к обеду. Попробуйте кайсендон — миску риса с ассорти из моря: уни тает на языке, оторо — самая жирная часть тунца. Рис в соевый соус не макают: слегка обмакивают рыбу. Настоящий васаби тертый, бледно-зелёный; яркая паста из тюбика — заменитель. Утром рыба свежее, вечером очереди короче — выбирайте по своему режиму. Рынок шумный и пахнет морем, но это лучший способ понять Токио через вкус.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/sushitokyo-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/sushitokyo-3.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try foodCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/francewine-1.jpg",
                              title: "Винные дороги Прованса",
                              subtitle: "Как выбрать вино без сложных терминов",
                              date: seedDate(month: 3, day: 2),
                              readingTime: 8,
                              description: "Во Франции на этикетке чаще указывают регион, а не сорт винограда — это терруар, вкус места. Иерархия простая: столловое вино, затем IGP и AOC — чем выше статус, тем строже правила производства. В Бордо левый берег даёт мощные каберне, правый — мягче и раньше пьются. В Провансе розе сочетают с рыбой и оливками, красные — с тушёным мясом. Дегустация в шато не обязана стоить сотни евро: многие дома принимают по записи с небольшим набором бокалов. Держите бокал за ножку, декантируйте плотные красные молодым воздухом, при чоканье смотрите в глаза — так принято у местных.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/francewine-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/francewine-3.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try leisureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/nightlife-1.jpg",
                              title: "Фейсконтроль в клубах Берлина",
                              subtitle: "Дресс-код и правила у двери",
                              date: seedDate(month: 3, day: 14),
                              readingTime: 7,
                              description: "В Berghain, Tresor и похожих клубах дверь — отдельный ритуал. Одежда тёмная и простая: без блёсток, каблуков и «туристического» глянца. Лучше прийти вдвоём или одному — большие шумные компании реже проходят. В очереди не доставайте телефон: приватность ценят выше статуса. Внутри съёмка часто запрещена, на камеру клеят наклейку — это норма. Не спорьте с охраной и не предлагайте «решить вопрос» деньгами — в Берлине это только ухудшает впечатление. Отвечайте спокойно, без пафоса. Если не пустили — смените клуб, а не настроение: ночь в городе всё равно длинная.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/nightlife-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/nightlife-3.jpg"],
                              isPopular: true,
                              isHeadCell: true),
                         makeCell(categoryID: try leisureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/louvre-1.jpg",
                              title: "Лувр без бесконечных очередей",
                              subtitle: "Время входа и маршрут по залам",
                              date: seedDate(month: 3, day: 28),
                              readingTime: 6,
                              description: "Лувр невозможно «пройти целиком» за один день — и не нужно. Вход через Carrousel du Louvre под пирамидой часто быстрее главной очереди. В будни после 17:00 залов меньше — Мона Лиза и Венера смотрятся спокойнее. Скачайте официальный аудиогид заранее, чтобы не брать очередь за плеер. Выберите три-четыре отдела: античность, живопись, восточное искусство — и остановитесь там. Билет онлайн с тайм-слотом экономит часы. Бесплатные вечера бывают в определённые дни — проверьте сайт музея. Лучший сувенир — не усталость, а пара картин, которые запомнились, и вечерняя прогулка по Сене.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/louvre-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/louvre-3.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try leisureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/disneyland-1.jpg",
                              title: "Диснейленд без часов ожидания",
                              subtitle: "FastPass и Single Rider на практике",
                              date: seedDate(month: 4, day: 5),
                              readingTime: 9,
                              description: "В крупных парках очереди по полтора часа — норма без плана. Single Rider — отдельная линия для одиночек: вы садитесь не рядом с друзьями, но проходите в разы быстрее. Начинайте день с самых популярных аттракционов у входа или идите от дальнего конца к выходу — так вы обгоняете толпу, которая только проснулась. Приложение парка показывает время ожидания в реальном времени — обновляйте маршрут каждый час. Билеты и бронь отеля с ранним входом окупаются в пик сезона. Еду удобнее брать вне главной аллеи: там дешевле и спокойнее. Запланируйте тихий перерыв в середине дня — иначе к вечеру сил не останется на парад.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/disneyland-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/disneyland-3.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try leisureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/portugal-1.jpg",
                              title: "Настоящее фаду в Лиссабоне",
                              subtitle: "Как найти таверну вне туристических зон",
                              date: seedDate(month: 4, day: 18),
                              readingTime: 6,
                              description: "Фаду — не шоу с микрофонами в центре, а тихая песня о судьбе в полутёмной комнате. Обходите рестораны с зазывалами у двери и неоновыми «Fado Show». Ищите маленькие casa de fado в Алфаме и Моурарии, где поют хозяин или соседи без сцены. Во время песни в зале тишина: официанты замирают, свет приглушают. Не фотографируйте вспышкой и не разговаривайте — это часть уважения. Закажите вино и тапас заранее, пока выступление не началось. Так вы услышите саудade — ту самую светлую грусть Португалии, которую не переводят, а чувствуют.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/portugal-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/portugal-3.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try leisureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/surfing-1.jpg",
                              title: "Серфинг на Бали для новичков",
                              subtitle: "Школы волн и этикет на воде",
                              date: seedDate(month: 5, day: 1),
                              readingTime: 8,
                              description: "Бали идеален для первых волн, но океан не прощает самоуверенности. Начинайте на Куте или Чангу: песчаное дно и пологий прибой. Улувату и другие рифы — для опытных. Берите сертифицированную школу, а не «дешёвую доску» у случайного инструктора на пляже. Читайте прогноз: высота волны, ветер, отлив. На воде у кого волна — тот и едет; подрезать (drop in) нельзя. Держитесь в стороне от зоны обрушения, чтобы доска соседа не ударила. В прокате возьмите лиш и крем SPF 50+ — солнце здесь жёсткое. Первый удачный проезд запоминается надолго — главное, вернуться на берег без травм.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/surfing-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/surfing-3.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try fraudCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/fraud-1.jpg",
                              title: "Как распознать уличного мошенника",
                              subtitle: "Схемы обмана от Парижа до Бангкока",
                              date: seedDate(month: 1, day: 12),
                              readingTime: 7,
                              description: "В поездке мошенники играют на вежливости и растерянности. Остерегайтесь «бесплатного»: браслеты на запястье у Сакре-Кёр, цветы в руку, фото с костюмированным персонажем — потом назовут сумму. Фальшивые полицейские просят проверить купюры; зазывалы говорят, что музей закрыт, и ведут в магазин; у банкомата «помощник» смотрит PIN. Говорите «нет» спокойно и громко, не отдавайте паспорт и кошелёк незнакомцам. Деньги меняйте в банке, а не у человека с «выгодным курсом». Если ситуация накаляется — уходите в людное место. Знание схем дешевле, чем один испорченный день отпуска.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/fraud-2.jpg"],
                              isPopular: true,
                              isHeadCell: true),
                         makeCell(categoryID: try fraudCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/security-1.jpg",
                              title: "Цифровая безопасность в пути",
                              subtitle: "VPN Wi-Fi и защита документов в дороге",
                              date: seedDate(month: 2, day: 8),
                              readingTime: 6,
                              description: "Публичный Wi-Fi в аэропорту и отеле удобен, но трафик могут перехватить. Не входите в банк и не платите картой без VPN. Двухфакторную аутентификацию включите до вылета; пароли храните в менеджере, а не в заметках. Сканы паспорта и билетов — в зашифрованном облаке: при краже телефона копии останутся доступны с другого устройства. USB-зарядки в зонах ожидания — риск «juice jacking»: лучше свой блок и кабель в розетку. Обновите систему и отключите автоподключение к открытым сетям. Так вы не потеряете деньги и доступ к аккаунтам в самый неподходящий момент поездки.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/security-2.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try healthCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/jetlag-1.jpg",
                              title: "Как обмануть джетлаг",
                              subtitle: "Быстрая адаптация к новому часовому поясу",
                              date: seedDate(month: 1, day: 25),
                              readingTime: 6,
                              description: "Джетлаг съедает первые дни отпуска. За два-три дня до вылета сдвигайте сон на час в сторону нового пояса. В самолёте пейте воду, откажитесь от алкоголя и лишнего кофе — они усиливают обезвоживание. После прилёта не ложитесь спать до местной ночи: прогулка на солнце помогает сбросить мелатонин. Дневной сон — не больше двадцати минут, иначе проснётесь разбитыми. Мелатонин по короткому курсу иногда помогает, но схему лучше согласовать с врачом. Свет, вода и режим важнее таблеток — организм подстроится быстрее, чем кажется в первый день.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/jetlag-2.jpg"],
                              isPopular: true,
                              isHeadCell: true),
                         makeCell(categoryID: try healthCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/firstaid-1.jpg",
                              title: "Аптечка путешественника",
                              subtitle: "Что взять чтобы не искать аналоги за рубежом",
                              date: seedDate(month: 3, day: 6),
                              readingTime: 7,
                              description: "В чужой аптеке то же действующее вещество часто называется иначе, а рецептурные препараты могут не продать. База: жаропонижающее, сорбенты, антигистамин, пластыри разного размера, обезболивающее. Рецептурные лекарства везите с запасом в оригинальной упаковке и с инструкцией — так проще на таможне. Добавьте средство от укачивания, если планируете серпантины или лодки. Электронный термометр компактнее ртутного. Соберите аптечку в плоском косметичке, а не в коробке от обуви: половина чемодана для лекарств не нужна, нужны только проверенные позиции.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/firstaid-2.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try healthCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/longflight-1.jpg",
                              title: "Долгий перелет без отёков",
                              subtitle: "Сосуды кожа и комфорт на высоте",
                              date: seedDate(month: 3, day: 20),
                              readingTime: 5,
                              description: "В салоне воздух очень сухой, а сидение часами нагружает вены. Каждый час вращайте стопами и вставайте в проход, если можно. Компрессионные носки снижают отёки на длинных рейсах. Пейте воду, увлажняйте кожу кремом или термальной водой; тяжёлые маски не обязательны. Линзы лучше сменить на очки до посадки — глаза сохнут сильнее. При регистрации берите проход, если нужно часто разминаться, или место у иллюминатора, если важен опор для сна. Лёгкая растяжка в терминале перед посадкой дешевле, чем таблетки от боли в спине на следующий день.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/longflight-2.jpg"],
                              isPopular: false,
                              isHeadCell: false),
                         makeCell(categoryID: try healthCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/hygiene-1.jpg",
                              title: "Гигиена в тропиках",
                              subtitle: "Как избежать кишечных инфекций в поездке",
                              date: seedDate(month: 4, day: 12),
                              readingTime: 6,
                              description: "В тропиках большинство расстройств идёт от воды. Правило: сварить, пожарить, очистить или не есть. Пейте воду с целой заводской пломбой, ею же чистите зубы. Лёд в уличных коктейлях часто из сырой воды — откажитесь. Салаты и зелень, промытые из-под крана, рискованнее жареного. Антисептик для рук уместен до еды, но не заменяет мытьё. Не купайтесь в стоячих пресных водоёмах после дождя. При первых симптомах пейте электролиты и сорбенты, не геройствуйте с обезвоживанием — так сохраните дни отпуска, а не только настроение.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/hygiene-2.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try cultureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/signlanguage-1.jpg",
                              title: "Жесты которые обидят за границей",
                              subtitle: "Что нельзя показывать в разных странах",
                              date: seedDate(month: 2, day: 14),
                              readingTime: 6,
                              description: "Привычный жест дома за границей может оскорбить. «ОК» кольцом из пальцев в Бразилии и Турции — грубость. Большой палец вверх в Иране и Афганистане — как средний палец у нас. В Болгарии кивок головой значит «нет», а не «да». В Таиланде не указывайте на людей пальцем — лучше ладонью. В буддийских странах не трогайте чужую голову, даже ребёнка: это священная часть тела. Деньги, еду и визитки в Юго-Восточной Азии и на Ближнем Востоке подавайте правой рукой. Перед поездкой пробегите список жестов страны — дешевле, чем извиняться на языке, которого вы не знаете.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/signlanguage-2.jpg"],
                              isPopular: true,
                              isHeadCell: true),
                         makeCell(categoryID: try cultureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/shrines-1.jpg",
                              title: "Храмы и святыни туриста",
                              subtitle: "Одежда обувь и тишина внутри",
                              date: seedDate(month: 3, day: 11),
                              readingTime: 6,
                              description: "В действующих храмах важны скромность и тишина. Плечи и колени закрыты у всех; в мечетях и православных храмах женщинам нужен платок на голову. В буддийских и индуистских святынях снимайте обувь у входа. В Таиланде не направляйте стопы на статую Будды — садитесь ногами от неё. Обходите ступу по часовой стрелке. Фото без вспышки, где разрешено; у алтаря селфи часто воспринимают как неуважение. Говорите тихо, телефон на беззвучный. Так вы увидите живую веру, а не спор с охраной у двери.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/shrines-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/shrines-3.jpg"],
                              isPopular: true,
                              isHeadCell: false),
                         makeCell(categoryID: try cultureCategory.requireID(),
                              image: "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/japan-1.jpg",
                              title: "Этикет в Японии для туриста",
                              subtitle: "Метро поклоны и правила с палочками",
                              date: seedDate(month: 4, day: 24),
                              readingTime: 7,
                              description: "В метро Токио и Осаки тихо: разговоры по телефону в вагоне — дурной тон. Поклоны бывают лёгкими и глубокими — кивок достаточно в быту. Палочки не втыкайте вертикально в рис и не передавайте еду с палочек на палочки — это табу. Миску с рисом не поднимают к губам. В рёкане снимайте обувь на татами, юкату надевают левым направом. В онсене сначала тщательно моются под душем, потом заходят в общую ванну; полотенце в воду не опускают. Спокойствие и уважение к пространству других ценят выше идеального японского.",
                              images: ["https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/japan-2.jpg", "https://s3.twcstorage.ru/20cfb482-4656-480c-971f-c7954afe05b1/japan-3.jpg"],
                              isPopular: true,
                              isHeadCell: false)]

        for cell in cellsData {
            try await cell.save(on: db)
        }
    }

    private func makeCell(categoryID: Category.IDValue,
                          image: String,
                          title: String,
                          subtitle: String,
                          date: Date,
                          readingTime: Int,
                          description: String,
                          images: [String],
                          isPopular: Bool = false,
                          isHeadCell: Bool = false) -> Cell {
        Cell(title: title,
             subtitle: subtitle,
             description: description,
             categoryID: categoryID,
             date: date,
             readingTime: readingTime,
             image: image,
             images: images,
             isPopular: isPopular,
             isHeadCell: isHeadCell)
    }

    private func seedDate(month: Int, day: Int) -> Date {
        var components = DateComponents()
        components.calendar = Calendar(identifier: .gregorian)
        components.timeZone = TimeZone(secondsFromGMT: 0)
        components.year = 2026
        components.month = month
        components.day = day
        components.hour = 12
        return components.date!
    }
}
