services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      PORT: "8080"
      POSTGRESQL_CA_CERT_PATH: /app/ca.crt

  migrate:
    build: .
    env_file: .env
    environment:
      POSTGRESQL_CA_CERT_PATH: /app/ca.crt
    command: ["migrate", "--yes"]
    profiles:
      - migrate
